import { Field, Int, ObjectType } from '@nestjs/graphql';
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import * as mongoose from 'mongoose';

export type UserDocument = User & mongoose.Document;

@ObjectType()
@Schema()
export class User {
  // auto-generated by mongodb, hence no need to ownself define
  _id: string;
  @Field()
  @Prop({ unique: true })
  username: string;
  @Field()
  @Prop({ unique: true })
  email: string;
  @Field()
  @Prop()
  password: string;
  @Field()
  @Prop()
  role: string;
  @Field()
  @Prop()
  is_activated: boolean;
  @Field()
  @Prop()
  first_name: string;
  @Field()
  @Prop()
  last_name: string;
  @Field()
  @Prop()
  nickname: string;
  @Field()
  @Prop()
  profilePicture: string;
  @Field()
  @Prop()
  about: string;
  @Field()
  @Prop()
  gender: string;
  @Field()
  @Prop()
  dob: Date;
  @Field()
  @Prop()
  occupation: string;
  @Field()
  @Prop()
  phone: string;
  @Field()
  @Prop()
  facebook_link: string;
  @Field()
  @Prop()
  twitter_link: string;
  @Field()
  @Prop()
  instagram_link: string;
  @Field()
  @Prop()
  linkedin_link: string;
  @Field()
  @Prop()
  is_verified: boolean;
  @Field()
  @Prop()
  created_on: Date;
}

export const UserSchema = SchemaFactory.createForClass(User);
