import { Field, ObjectType } from '@nestjs/graphql';
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import * as mongoose from 'mongoose';

export type UserDocument = User & mongoose.Document;

@ObjectType()
@Schema()
export class User {
  // auto-generated by mongodb, hence no need to self-define
  _id: string;
  @Field()
  @Prop({ unique: true })
  username: string;
  @Field()
  @Prop({ unique: true })
  email: string;
  @Field()
  @Prop()
  password: string;
  @Field()
  @Prop()
  role: string;
  @Field()
  @Prop()
  is_activated: boolean;
  @Field()
  @Prop()
  name: string;
  @Field()
  @Prop()
  profile_picture: string;
  @Field()
  @Prop()
  gender: string;
  @Field()
  @Prop()
  dob: Date;
  @Field()
  @Prop()
  occupation: string;
  @Field()
  @Prop()
  created_on: Date;
}

export const UserSchema = SchemaFactory.createForClass(User);
