import { Field, ID, ObjectType } from '@nestjs/graphql';
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import * as mongoose from 'mongoose';

export type UserDocument = User & mongoose.Document;

@ObjectType()
@Schema({ timestamps: true })
export class User {
  // auto-generated by mongodb, hence no need to self-define
  @Field((type) => ID)
  _id: string;
  @Field()
  @Prop({ unique: true, required: true })
  username: string;
  @Field()
  @Prop({ unique: true, required: true })
  email: string;
  @Field()
  @Prop()
  password: string;
  @Field()
  @Prop()
  role: string;
  @Field()
  @Prop()
  is_activated: boolean;
  @Field()
  @Prop()
  name: string;
  @Field()
  @Prop()
  profile_picture: string;
  @Field()
  @Prop()
  gender: string;
  @Field()
  @Prop()
  dob: Date;
  @Field()
  @Prop()
  occupation: string;
}

export const UserSchema = SchemaFactory.createForClass(User);
