name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
      - name: Install global dependencies
        run: |
          npm install -g @nestjs/cli

      - name: Install dependencies, check formatting and build
        run: |
          npm install
          npm run check:format
          npm run build
