name: Deploy to dev server
on:
  push:
    branches:
      - master
jobs:
  deploy-dev:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Deploy to dev server
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.DEV_HOST }}
          USERNAME: root
          KEY: ${{ secrets.DEV_SSH_KEY }}
          script_stop: true
          script: |
            source ~/.zshrc && \
            cd ${{ secrets.REPO_DIR }} && \
            git checkout master && \
            git pull origin master && \
            nvm use && \
            npm i && \
            npm run build && \
            npm start
